#!/usr/bin/python

Import("env")

env.scene_sources = []

# Godot source files
env.add_source_files(env.scene_sources, "*.cpp")

lib = env.add_library("scene", env.scene_sources)
env.Prepend(LIBS=[lib])
